import type { Metadata } from "next";
import { DM_Mono } from "next/font/google";
import "./globals.css";
import { Navigation } from "./navigation";
import { Footer } from "../components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// DM Mono for sans-serif usage (replacing Manrope)
const dmMonoSans = DM_Mono({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500"], // Loading all available weights: light, regular, medium
});

// DM Mono for monospace usage
const dmMono = DM_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"], // Loading all available weights: light, regular, medium
});

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${dmMonoSans.variable} ${dmMono.variable} layout-body-container`}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
